### ISSUE TITLE
URL Parameters for Lat/Lon

### ISSUE THREAD

**Issue by ccmehil** [ccmehil/star_coords#4]
Have to consider that you may be in a field or somewhere else and therefore you will need a more precise Latitude and Longitude so need to add a URL parameter to give a more precise location.

**Comment by ccmehil** [comment]
Deterimine location from lat: 51.67135809731837 lon: 8.333513624067516 and alt: 74,0746078491211
----------------------------------------

> Exception occurred during processing of request from ('192.168.86.36', 65372)
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/dist-packages/astropy/coordinates/earth.py", line 202, in __new__
>     self = cls.from_geocentric(*args, **kwargs)
> TypeError: from_geocentric() got an unexpected keyword argument 'lat'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/dist-packages/astropy/coordinates/earth.py", line 205, in __new__
>     self = cls.from_geodetic(*args, **kwargs)
>   File "/usr/local/lib/python3.9/dist-packages/astropy/coordinates/earth.py", line 297, in from_geodetic
>     lon = Angle(lon, u.degree, copy=False).wrap_at(180 * u.degree)
>   File "/usr/local/lib/python3.9/dist-packages/astropy/coordinates/angles.py", line 138, in __new__
>     return super().__new__(cls, angle, unit, dtype=dtype, copy=copy,
>   File "/usr/local/lib/python3.9/dist-packages/astropy/units/quantity.py", line 511, in __new__
>     raise TypeError("The value must be a valid Python or "
> TypeError: The value must be a valid Python or Numpy numeric type.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/socketserver.py", line 316, in _handle_request_noblock
>     self.process_request(request, client_address)
>   File "/usr/lib/python3.9/socketserver.py", line 347, in process_request
>     self.finish_request(request, client_address)
>   File "/usr/lib/python3.9/socketserver.py", line 360, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "/usr/lib/python3.9/socketserver.py", line 720, in __init__
>     self.handle()
>   File "/usr/lib/python3.9/http/server.py", line 427, in handle
>     self.handle_one_request()
>   File "/usr/lib/python3.9/http/server.py", line 415, in handle_one_request
>     method()
>   File "/home/pi/star_coords/server.py", line 138, in do_GET
>     self.respond()
>   File "/home/pi/star_coords/server.py", line 134, in respond
>     content = self.handle_http(200, 'text/html')
>   File "/home/pi/star_coords/server.py", line 114, in handle_http
>     location = EarthLocation(lat=latitude[0]*u.deg, lon=longitude[0]*u.deg, height=altitude[0]*u.m)
>   File "/usr/local/lib/python3.9/dist-packages/astropy/coordinates/earth.py", line 207, in __new__
>     raise TypeError('Coordinates could not be parsed as either '
> TypeError: Coordinates could not be parsed as either geocentric or geodetic, with respective exceptions "from_geocentric() got an unexpected keyword argument 'lat'" and "The value must be a valid Python or Numpy numeric type."

**Comment by ccmehil** [comment]
Coordinates could not be parsed as either geocentric or geodetic, with respective exceptions "from_geocentric() got an unexpected keyword argument 'lat'" and "The value must be a valid Python or Numpy numeric type."

In a test script

```
#!/usr/bin/env python

import os

# Astro
import numpy as np
import astropy.units as u
from astropy.time import Time
from astropy.coordinates import SkyCoord, EarthLocation, AltAz, solar_system_ephemeris
from astropy.coordinates import get_body_barycentric, get_body, get_moon

#Deterimine location from lat: 51.67135809731837 lon: 8.333513624067516 and alt: 74,998950958252
lat = 51.67135809731837
lon = 8.333513624067516
alt= 74,998950958252

print("Deterimine location from lat: %s lon: %s and alt: %s" % (lat, lon, alt))
location = EarthLocation(lat=lat*u.deg, lon=lon*u.deg, height=alt*u.m)
print("Location %r" % location)
```

This works fine with a good result

Location <EarthLocation [(3.92190353e+06, 5.74486884e+05, 4.98026655e+06),
                (6.12983191e+11, 8.97907866e+10, 7.83648490e+11)] m>

Not sure why from the URL parsed argument the error is throwing.

**Comment by ccmehil** [comment]
using int() 

> Exception occurred during processing of request from ('192.168.86.36', 65420)
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/socketserver.py", line 316, in _handle_request_noblock
>     self.process_request(request, client_address)
>   File "/usr/lib/python3.9/socketserver.py", line 347, in process_request
>     self.finish_request(request, client_address)
>   File "/usr/lib/python3.9/socketserver.py", line 360, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "/usr/lib/python3.9/socketserver.py", line 720, in __init__
>     self.handle()
>   File "/usr/lib/python3.9/http/server.py", line 427, in handle
>     self.handle_one_request()
>   File "/usr/lib/python3.9/http/server.py", line 415, in handle_one_request
>     method()
>   File "/home/pi/star_coords/server.py", line 138, in do_GET
>     self.respond()
>   File "/home/pi/star_coords/server.py", line 134, in respond
>     content = self.handle_http(200, 'text/html')
>   File "/home/pi/star_coords/server.py", line 114, in handle_http
>     location = EarthLocation(lat=int(latitude[0])*u.deg, lon=int(longitude[0])*u.deg) #, height=altitude[0]*u.m)
> ValueError: invalid literal for int() with base 10: '51.67135809731837'
>

**Comment by ccmehil** [comment]
Fixed location = EarthLocation(lat=int(float(latitude[0]))*u.deg, lon=int(float(longitude[0]))*u.deg, height=int(float(altitude[0]))*u.m)

int(float(...))
